### ISSUE TITLE
Could not read from repository

### ISSUE THREAD

**Issue by tercanfurkan** [mostjs/multicast#23]
It's not possible to npm install. I get this error:

```
npm ERR! git clone git@github.com:most/multicast ERROR: Repository not found.
npm ERR! git clone git@github.com:most/multicast fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:most/multicast 
npm ERR! git clone git@github.com:most/multicast Please make sure you have the correct access rights
npm ERR! git clone git@github.com:most/multicast and the repository exists.
npm ERR! addLocal Could not install most/multicast
npm ERR! Error: ENOENT, stat 'most/multicast'

**Comment by TylorS** [comment]
Hey @tercanfurkan the name of the organization `mostjs` with `js` at the end and not just `most`.

Please let us know if this solves your issue :)

**Comment by tercanfurkan** [comment]
Hey,

The npm package name still seems to be @most/multicast and the doc says `npm install @most/multicast`
https://www.npmjs.com/package/@most/multicast

I could not install with mostjs either. So far neither of these work:

```
$ npm install @most/multicast
npm ERR! git clone git@github.com:most/multicast ERROR: Repository not found.
npm ERR! git clone git@github.com:most/multicast fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:most/multicast 
npm ERR! git clone git@github.com:most/multicast Please make sure you have the correct access rights
npm ERR! git clone git@github.com:most/multicast and the repository exists.
npm ERR! addLocal Could not install most/multicast
npm ERR! Error: ENOENT, stat 'most/multicast'
```

And then `npm install @mostjs/multicast` or `npm install mostjs/multicast` does not work giving an ENOENT error:

```
npm ERR! addLocal Could not install mostjs/multicast
npm ERR! Error: ENOENT, stat 'mostjs/multicast'
```

It seems line mostjs/multicast does not even exist in npm registry.

Besides, I was actually trying to install [most package](https://www.npmjs.com/package/most) which internally requires `"@most/multicast": "^1.2.3"`

Have you recently changed the namespace to mostjs from most? It this why npm cannot find the repo?

**Comment by TylorS** [comment]
Oh no, we've not changed how its published to npm. I assumed that you were trying to pull from GitHub based on the vague error npm seems to give you. We'll look into it. 

Thanks for reporting!

**Comment by TylorS** [comment]
Hey @tercanfurkan, I'm currently unable to reproduce this. Is this still occurring for you?

**Comment by briancavalier** [comment]
Closing from lack of activity and not being able to reproduce.  Please feel free to reopen if you are still seeing an issue, @tercanfurkan.
